name: molevis
channels:
- conda-forge
dependencies:
- python=3.10
- rdkit
- pip
- pip:
- streamlit==1.26.0
- requests
- pubchempy
- py3Dmol
- psycopg2-binary
- sqlalchemy
- python-dotenv
- pandas
- Pillow